### ISSUE TITLE
[Feature] "Faster" backlight

### ISSUE THREAD

**Issue by benbender** [hieplpvip/AppleBacklightSmoother#4]
If you press and hold volume-hotkeys on a Hackintosh they are recognized very fast so you can adjust the volume simply by holding the key without a noticeable delay.

For brightness-keys there is a noticeable delay between the recognized keystrokes and I initially thought this kext would eliminate those delays to give a more "native" feel as its the same "experience" for volume- and brightness-keys on a genuine Mac.

I'm not entirely sure if this is possible without major effort and its surely a minor detail, but asking about the possibility doesn't cost :)

**Comment by hieplpvip** [comment]
Which laptop do you use?

**Comment by benbender** [comment]
Lenovo X1C6, 8550U Kaby-Lake-Refresh, UHD 620 PCIId 5917

And

Lenvovo T480, 8650U Kaby-Lake-Refresh, UHD 620 PCIId 5917

**Comment by hieplpvip** [comment]
Are backlight key events sent through PS2 or EC (_QXX)?

**Comment by benbender** [comment]
EC (Q14/Q15)

**Comment by hieplpvip** [comment]
With EC, we can't distinguish between key down and key up events, so each time you press the key, both key down and key up events have to be sent to macOS. Therefore, fast adjusting is not possible.

PS2 works differently. When you press the key, a key down event is sent. Key up event is only sent once you release the key.

You can work around this by mapping Fx keys to brightness keys with Karabiner-Elements.

P/s: I'm not sure if it's impossible to distinguish key down/up with EC. The thing is different vendors have different implementations. If it's possible, it probably requires a dedicated driver. Since I have Asus while you have Lenovo, there's not much I can help you.

**Comment by benbender** [comment]
Ah, I See. Thanks for the nice explanation. Maybe @zhen-zen can help to clarify the possibility as he worked on VoodooPS2 and is the creator of YogaSMC for Lenovo-Laptops.
